version: 2
jobs:
  build:
    machine: true
    steps:
      - *attach_workspace
      - run: ./bin/retry yarn test:jest

  check-i18n:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: bundle exec i18n-tasks check-normalized
      - run: bundle exec i18n-tasks unused -l en
      - run: bundle exec i18n-tasks check-consistent-interpolations

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
